/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFamilyMemberIdRouteImport } from './routes/_authenticated/family.$memberId'
import { Route as AuthenticatedFamilyNewRouteImport } from './routes/_authenticated/family.new'
import { Route as AuthenticatedPrescriptionsPrescriptionIdRouteImport } from './routes/_authenticated/prescriptions.$prescriptionId'
import { Route as AuthenticatedPrescriptionsNewRouteImport } from './routes/_authenticated/prescriptions.new'
import { Route as AuthenticatedFamilyMemberIdEditRouteImport } from './routes/_authenticated/family.$memberId.edit'
import { Route as AuthenticatedPrescriptionsPrescriptionIdEditRouteImport } from './routes/_authenticated/prescriptions.$prescriptionId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyMemberIdRoute =
  AuthenticatedFamilyMemberIdRouteImport.update({
    id: '/family/$memberId',
    path: '/family/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyNewRoute = AuthenticatedFamilyNewRouteImport.update({
  id: '/family/new',
  path: '/family/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrescriptionsPrescriptionIdRoute =
  AuthenticatedPrescriptionsPrescriptionIdRouteImport.update({
    id: '/prescriptions/$prescriptionId',
    path: '/prescriptions/$prescriptionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrescriptionsNewRoute =
  AuthenticatedPrescriptionsNewRouteImport.update({
    id: '/prescriptions/new',
    path: '/prescriptions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamilyMemberIdEditRoute =
  AuthenticatedFamilyMemberIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedFamilyMemberIdRoute,
  } as any)
const AuthenticatedPrescriptionsPrescriptionIdEditRoute =
  AuthenticatedPrescriptionsPrescriptionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPrescriptionsPrescriptionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/family/$memberId': typeof AuthenticatedFamilyMemberIdRouteWithChildren
  '/family/new': typeof AuthenticatedFamilyNewRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRouteWithChildren
  '/prescriptions/new': typeof AuthenticatedPrescriptionsNewRoute
  '/family/$memberId/edit': typeof AuthenticatedFamilyMemberIdEditRoute
  '/prescriptions/$prescriptionId/edit': typeof AuthenticatedPrescriptionsPrescriptionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/family/$memberId': typeof AuthenticatedFamilyMemberIdRouteWithChildren
  '/family/new': typeof AuthenticatedFamilyNewRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRouteWithChildren
  '/prescriptions/new': typeof AuthenticatedPrescriptionsNewRoute
  '/family/$memberId/edit': typeof AuthenticatedFamilyMemberIdEditRoute
  '/prescriptions/$prescriptionId/edit': typeof AuthenticatedPrescriptionsPrescriptionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/family/$memberId': typeof AuthenticatedFamilyMemberIdRouteWithChildren
  '/_authenticated/family/new': typeof AuthenticatedFamilyNewRoute
  '/_authenticated/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRouteWithChildren
  '/_authenticated/prescriptions/new': typeof AuthenticatedPrescriptionsNewRoute
  '/_authenticated/family/$memberId/edit': typeof AuthenticatedFamilyMemberIdEditRoute
  '/_authenticated/prescriptions/$prescriptionId/edit': typeof AuthenticatedPrescriptionsPrescriptionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/search'
    | '/settings'
    | '/family/$memberId'
    | '/family/new'
    | '/prescriptions/$prescriptionId'
    | '/prescriptions/new'
    | '/family/$memberId/edit'
    | '/prescriptions/$prescriptionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/search'
    | '/settings'
    | '/family/$memberId'
    | '/family/new'
    | '/prescriptions/$prescriptionId'
    | '/prescriptions/new'
    | '/family/$memberId/edit'
    | '/prescriptions/$prescriptionId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/family/$memberId'
    | '/_authenticated/family/new'
    | '/_authenticated/prescriptions/$prescriptionId'
    | '/_authenticated/prescriptions/new'
    | '/_authenticated/family/$memberId/edit'
    | '/_authenticated/prescriptions/$prescriptionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/$memberId': {
      id: '/_authenticated/family/$memberId'
      path: '/family/$memberId'
      fullPath: '/family/$memberId'
      preLoaderRoute: typeof AuthenticatedFamilyMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/new': {
      id: '/_authenticated/family/new'
      path: '/family/new'
      fullPath: '/family/new'
      preLoaderRoute: typeof AuthenticatedFamilyNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescriptions/$prescriptionId': {
      id: '/_authenticated/prescriptions/$prescriptionId'
      path: '/prescriptions/$prescriptionId'
      fullPath: '/prescriptions/$prescriptionId'
      preLoaderRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescriptions/new': {
      id: '/_authenticated/prescriptions/new'
      path: '/prescriptions/new'
      fullPath: '/prescriptions/new'
      preLoaderRoute: typeof AuthenticatedPrescriptionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family/$memberId/edit': {
      id: '/_authenticated/family/$memberId/edit'
      path: '/edit'
      fullPath: '/family/$memberId/edit'
      preLoaderRoute: typeof AuthenticatedFamilyMemberIdEditRouteImport
      parentRoute: typeof AuthenticatedFamilyMemberIdRoute
    }
    '/_authenticated/prescriptions/$prescriptionId/edit': {
      id: '/_authenticated/prescriptions/$prescriptionId/edit'
      path: '/edit'
      fullPath: '/prescriptions/$prescriptionId/edit'
      preLoaderRoute: typeof AuthenticatedPrescriptionsPrescriptionIdEditRouteImport
      parentRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRoute
    }
  }
}

interface AuthenticatedFamilyMemberIdRouteChildren {
  AuthenticatedFamilyMemberIdEditRoute: typeof AuthenticatedFamilyMemberIdEditRoute
}

const AuthenticatedFamilyMemberIdRouteChildren: AuthenticatedFamilyMemberIdRouteChildren =
  {
    AuthenticatedFamilyMemberIdEditRoute: AuthenticatedFamilyMemberIdEditRoute,
  }

const AuthenticatedFamilyMemberIdRouteWithChildren =
  AuthenticatedFamilyMemberIdRoute._addFileChildren(
    AuthenticatedFamilyMemberIdRouteChildren,
  )

interface AuthenticatedPrescriptionsPrescriptionIdRouteChildren {
  AuthenticatedPrescriptionsPrescriptionIdEditRoute: typeof AuthenticatedPrescriptionsPrescriptionIdEditRoute
}

const AuthenticatedPrescriptionsPrescriptionIdRouteChildren: AuthenticatedPrescriptionsPrescriptionIdRouteChildren =
  {
    AuthenticatedPrescriptionsPrescriptionIdEditRoute:
      AuthenticatedPrescriptionsPrescriptionIdEditRoute,
  }

const AuthenticatedPrescriptionsPrescriptionIdRouteWithChildren =
  AuthenticatedPrescriptionsPrescriptionIdRoute._addFileChildren(
    AuthenticatedPrescriptionsPrescriptionIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedFamilyMemberIdRoute: typeof AuthenticatedFamilyMemberIdRouteWithChildren
  AuthenticatedFamilyNewRoute: typeof AuthenticatedFamilyNewRoute
  AuthenticatedPrescriptionsPrescriptionIdRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRouteWithChildren
  AuthenticatedPrescriptionsNewRoute: typeof AuthenticatedPrescriptionsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedFamilyMemberIdRoute:
    AuthenticatedFamilyMemberIdRouteWithChildren,
  AuthenticatedFamilyNewRoute: AuthenticatedFamilyNewRoute,
  AuthenticatedPrescriptionsPrescriptionIdRoute:
    AuthenticatedPrescriptionsPrescriptionIdRouteWithChildren,
  AuthenticatedPrescriptionsNewRoute: AuthenticatedPrescriptionsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
